-- Sample tours data with domestic, inbound, and outbound categories
INSERT INTO tours (
    title,
    slug,
    description,
    price,
    duration,
    max_participants,
    included,
    excluded,
    itinerary,
    images,
    status,
    featured,
    category,
    location,
    created_at,
    updated_at
) VALUES
-- DOMESTIC TOURS
(
    'Ha Long Bay 2-Day Cruise Adventure',
    'ha-long-bay-2-day-cruise',
    'Explore the UNESCO World Heritage site of Ha Long Bay with its emerald waters and towering limestone pillars. This 2-day cruise includes cave exploration, kayaking, and traditional Vietnamese cuisine.',
    299.00,
    '2 days, 1 night',
    20,
    '["Luxury cruise accommodation", "All meals included", "Professional English-speaking guide", "Kayaking equipment", "Cave entrance fees", "Round-trip transportation from Hanoi"]',
    '["Personal expenses", "Beverages (except welcome drink)", "Tips for guide and crew", "Travel insurance"]',
    '{"day1": {"morning": "Departure from Hanoi to Ha Long Bay", "afternoon": "Board cruise ship, lunch, visit Sung Sot Cave", "evening": "Sunset party, dinner on board"}, "day2": {"morning": "Tai Chi session, breakfast, kayaking at Luon Cave", "afternoon": "Brunch, return to Hanoi"}}',
    '["https://images.unsplash.com/photo-1528127269322-539801943592?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80", "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    true,
    'domestic',
    'Ha Long Bay, Vietnam',
    datetime('now', '-30 days'),
    datetime('now', '-30 days')
),
(
    'Sapa Trekking & Cultural Discovery',
    'sapa-trekking-cultural-discovery',
    'Experience the stunning terraced rice fields and rich cultural heritage of Sapa. Trek through ethnic minority villages and stay in traditional homestays.',
    189.00,
    '3 days, 2 nights',
    15,
    '["Professional trekking guide", "Homestay accommodation", "All meals", "Transportation from Hanoi", "Entrance fees", "Porter service"]',
    '["Personal expenses", "Alcoholic beverages", "Tips", "Travel insurance", "Optional activities"]',
    '{"day1": {"morning": "Hanoi to Sapa by bus", "afternoon": "Check-in, Cat Cat village trek", "evening": "Traditional dinner with local family"}, "day2": {"morning": "Lao Chai to Ta Van village trek", "afternoon": "Homestay experience, cultural activities", "evening": "Local dinner and traditional music"}, "day3": {"morning": "Silver Waterfall and Heaven Gate visit", "afternoon": "Return to Hanoi"}}',
    '["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80", "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    true,
    'domestic',
    'Sapa, Vietnam',
    datetime('now', '-25 days'),
    datetime('now', '-25 days')
),
(
    'Mekong Delta Day Trip',
    'mekong-delta-day-trip',
    'Discover the floating markets, fruit orchards, and traditional villages of the Mekong Delta. Experience local life along Vietnam''s vital waterway.',
    79.00,
    '1 day',
    25,
    '["Air-conditioned transportation", "Boat trips", "Professional guide", "Traditional lunch", "Fruit tasting", "Entrance fees"]',
    '["Personal expenses", "Beverages", "Tips", "Travel insurance"]',
    '{"day1": {"morning": "Departure from Ho Chi Minh City, visit Cai Rang floating market", "afternoon": "Fruit farm visit, traditional village tour, coconut candy workshop", "evening": "Return to Ho Chi Minh City"}}',
    '["https://images.unsplash.com/photo-1583417319070-4a69db38a482?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    false,
    'domestic',
    'Mekong Delta, Vietnam',
    datetime('now', '-20 days'),
    datetime('now', '-20 days')
),

-- INBOUND TOURS (for foreign visitors coming to Vietnam)
(
    'Vietnam Highlights 10-Day Tour',
    'vietnam-highlights-10-day',
    'The ultimate Vietnam experience covering Hanoi, Ha Long Bay, Hoi An, and Ho Chi Minh City. Perfect introduction to Vietnam''s culture, history, and natural beauty.',
    1299.00,
    '10 days, 9 nights',
    18,
    '["4-star hotel accommodation", "All domestic flights", "Professional English-speaking guides", "All entrance fees", "Daily breakfast", "Selected lunches and dinners", "Transportation", "Ha Long Bay cruise"]',
    '["International flights", "Visa fees", "Personal expenses", "Tips", "Travel insurance", "Drinks with meals"]',
    '{"day1": "Arrival in Hanoi, city tour", "day2": "Hanoi to Ha Long Bay cruise", "day3": "Ha Long Bay to Hanoi, fly to Da Nang", "day4": "Hoi An ancient town tour", "day5": "My Son Sanctuary day trip", "day6": "Hoi An to Ho Chi Minh City", "day7": "Ho Chi Minh City tour", "day8": "Cu Chi Tunnels and Mekong Delta", "day9": "Free day for shopping", "day10": "Departure"}',
    '["https://images.unsplash.com/photo-1528127269322-539801943592?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80", "https://images.unsplash.com/photo-1583417319070-4a69db38a482?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80", "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    true,
    'inbound',
    'Vietnam (Multi-city)',
    datetime('now', '-15 days'),
    datetime('now', '-15 days')
),
(
    'Northern Vietnam Adventure',
    'northern-vietnam-adventure',
    'Explore the mountainous regions of Northern Vietnam including Sapa, Ha Giang Loop, and Ban Gioc Waterfall. Adventure tour for active travelers.',
    899.00,
    '7 days, 6 nights',
    12,
    '["Hotel and homestay accommodation", "All transportation", "Professional guide", "All meals", "Entrance fees", "Motorbike rental for Ha Giang Loop"]',
    '["International flights", "Visa fees", "Personal expenses", "Tips", "Travel insurance", "Alcoholic beverages"]',
    '{"day1": "Hanoi arrival and orientation", "day2": "Hanoi to Sapa, village trekking", "day3": "Sapa to Ha Giang", "day4": "Ha Giang Loop - Dong Van", "day5": "Dong Van to Meo Vac to Ha Giang", "day6": "Ha Giang to Hanoi via Ban Gioc Waterfall", "day7": "Hanoi departure"}',
    '["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    false,
    'inbound',
    'Northern Vietnam',
    datetime('now', '-10 days'),
    datetime('now', '-10 days')
),

-- OUTBOUND TOURS (for Vietnamese going abroad)
(
    'Japan Cherry Blossom Tour',
    'japan-cherry-blossom-tour',
    'Experience Japan during the magical cherry blossom season. Visit Tokyo, Kyoto, and Mount Fuji with peak sakura viewing opportunities.',
    2199.00,
    '8 days, 7 nights',
    20,
    '["4-star hotel accommodation", "Daily breakfast", "Selected meals", "Professional Vietnamese-speaking guide", "All transportation in Japan", "Entrance fees", "JR Pass"]',
    '["International flights", "Japan visa fees", "Personal expenses", "Tips", "Travel insurance", "Some meals"]',
    '{"day1": "Arrival in Tokyo, city orientation", "day2": "Tokyo sightseeing - Senso-ji, Imperial Palace", "day3": "Mount Fuji and Hakone day trip", "day4": "Tokyo to Kyoto by bullet train", "day5": "Kyoto temples and bamboo forest", "day6": "Nara day trip - deer park and Todai-ji", "day7": "Osaka castle and Dotonbori", "day8": "Departure from Osaka"}',
    '["https://images.unsplash.com/photo-1522383225653-ed111181a951?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80", "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    true,
    'outbound',
    'Japan (Tokyo, Kyoto, Osaka)',
    datetime('now', '-8 days'),
    datetime('now', '-8 days')
),
(
    'Thailand Beach & Culture Escape',
    'thailand-beach-culture-escape',
    'Combine Bangkok''s vibrant culture with Phuket''s pristine beaches. Perfect blend of sightseeing and relaxation.',
    1099.00,
    '6 days, 5 nights',
    25,
    '["4-star hotel accommodation", "Daily breakfast", "Airport transfers", "City tours", "Temple visits", "Island hopping tour", "Professional guide"]',
    '["International flights", "Thailand visa", "Personal expenses", "Tips", "Travel insurance", "Lunch and dinner (except specified)"]',
    '{"day1": "Bangkok arrival, evening street food tour", "day2": "Bangkok temples and Grand Palace", "day3": "Bangkok to Phuket, beach relaxation", "day4": "Phi Phi Islands day tour", "day5": "Free day in Phuket", "day6": "Departure"}',
    '["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    false,
    'outbound',
    'Thailand (Bangkok, Phuket)',
    datetime('now', '-5 days'),
    datetime('now', '-5 days')
),
(
    'Singapore Malaysia Highlights',
    'singapore-malaysia-highlights',
    'Explore the modern marvels of Singapore and the cultural diversity of Kuala Lumpur in this exciting Southeast Asian adventure.',
    949.00,
    '5 days, 4 nights',
    30,
    '["3-star hotel accommodation", "Daily breakfast", "City tours", "Gardens by the Bay", "Petronas Towers visit", "Airport transfers", "Professional guide"]',
    '["International flights", "Visa fees", "Personal expenses", "Tips", "Travel insurance", "Most meals"]',
    '{"day1": "Singapore arrival, Marina Bay area", "day2": "Singapore city tour, Sentosa Island", "day3": "Singapore to Kuala Lumpur", "day4": "KL city tour, Batu Caves", "day5": "Departure from Kuala Lumpur"}',
    '["https://images.unsplash.com/photo-1525625293386-3f8f99389edd?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"]',
    'active',
    false,
    'outbound',
    'Singapore & Malaysia',
    datetime('now', '-3 days'),
    datetime('now', '-3 days')
);
